name: 'PR'
description: 'basic PR steps'
runs:
  using: "composite"
  steps:
    - name: "Setup npm"
      shell: bash
      run: |
        # To deploy the application with the latest changes, packages versions must be up to date.
        npm set @zidabah:registry=https://npm.pkg.github.com
        npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"


    - name: "Install dependencies"
      shell: bash
      run: |
        npm ci