name: 'Setup Node and NPM'
description: 'Facilitate the setup of Node, NPM and dependency installation process for'
inputs:
  gh_token:
    description: "GitHub Token for authentication to install private packages from GitHub Packages."
    required: true
runs:
  using: "composite"
  steps:
    - name: "Setup node"
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        registry-url: https://npm.pkg.github.com
        node-version: 18.15.0

    - name: "Setup npm"
      shell: bash
      run: |
        # To deploy the application with the latest changes, packages versions must be up to date.
        npm set @zidabah:registry=https://npm.pkg.github.com
        npm set "//npm.pkg.github.com/:_authToken=${{ inputs.gh_token }}"

    - name: "Install Dependencies"
      shell: bash
      run: npm ci