name: Deploy

on:
  workflow_run:
    workflows:  [Deploy Jekyll with GitHub Pages]
    types:
      - completed

env:
  NODE_AUTH_TOKEN: ${{ github.token }}

permissions: write-all

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          path: ./documentation
          name: 'github-pages-1'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Extract documentation artifact
        shell: bash
        run: |
          ls -l
          echo "Test test test"
          ls -l ./documentation
          tar -xf ./documentation/artifact.tar -C ./documentation

      - name: Download doc artifact
        uses: actions/download-artifact@v4
        with:
          path: ./document
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: 'github-pages-2'
          run-id: ${{ github.event.workflow_run.id }}

      - name: Extract documentation artifact
        run: tar -xf ./document/artifact.tar -C ./document

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation
          user_name: GitHub Actions
          user_email: actions@github.com
          destination_dir: documentation
#          keep_files: true
          publish_branch: gh-pages-1 # New branch for documentation

      - name: Deploy unit test reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./document
          user_name: GitHub Actions
          user_email: actions@github.com
          destination_dir: document
#          keep_files: true
          publish_branch: gh-pages-1 # New branch for unit test reports