name: Version bump

on:
  workflow_call:
    inputs:
      project:
        description: The project to run the version bump
        required: true
        type: string

permissions: write-all

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: "Update package.json with latest library version"
        if: env.NO_CHANGED_PACKAGES != 'true'
        run: |
          # To deploy the application with the latest changes, packages versions must be up to date.
          package_names=("date-renderer" "date-logic") # List of package names to update
            
          # To deploy the application with the latest changes, packages versions must be up to date.
          for pkg in "${package_names[@]}"; do
          latest_version=$(npm view "@zidabah/$pkg" version)
          jq --arg latest_version "$latest_version" ".dependencies[\"@zidabah/$pkg\"] = \$latest_version" package.json > package.json.tmp
          mv package.json.tmp package.json
          done
            
          # note: clean up temporary files
          rm -f package.json.tmp
          
          # note: install dependencies with the updated package.json
          npm install

      - name: "Commit and push changes"
        if: env.NO_CHANGED_PACKAGES != 'true'
        run: |
          # note: to deploy the application with the latest changes, packages versions must be up to date.
          git add package.json package-lock.json
          git commit -m "Update libraries to the latest version"
          git push
