name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches:
      - ZEN-3623
      - dev

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_AUTH_TOKEN: ${{ github.token }}

permissions:
  contents: read
  pages: write
  packages: read
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and npm
        uses: ./.github/actions/pr-preparation
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Compodoc documentation
        run: npm run compodoc

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./documentation

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
