name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches:
      - ZEN-3623
      - dev

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_AUTH_TOKEN: ${{ github.token }}

permissions: write-all

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and npm
        uses: ./.github/actions/pr-preparation
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Compodoc documentation
        run: npm run compodoc

      - name: Generate Compodoc documentation 2
        run: npx compodoc -p tsconfig.doc.json -d docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./documentation
          name: 'github-pages-1'

      - name: Upload artifact 2
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
          name: 'github-pages-2'

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          path: ./documentation
          name: 'github-pages-1'

      - name: Download doc artifact
        uses: actions/download-artifact@v4
        with:
          path: ./docs
          name: 'github-pages-2'

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation
          user_name: GitHub Actions
          user_email: actions@github.com
#          cname: example.com # if you have a custom domain, add it here
          publish_branch: gh-pages-documentation # New branch for documentation

      - name: Deploy unit test reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: GitHub Actions
          user_email: actions@github.com
#          cname: example.com # if you have a custom domain, add it here
          publish_branch: gh-pages-reports # New branch for unit test reports