name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches:
      - dev

env:
  NODE_AUTH_TOKEN: ${{ github.token }}

permissions: write-all

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and npm
        uses: ./.github/actions/pr-preparation
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Compodoc documentation
        run: npm run compodoc

      - name: Generate Compodoc documentation 2
        run: npx compodoc -p tsconfig.doc.json -d document

#      - name: Setup Pages
#        uses: actions/configure-pages@v4
#
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./documentation
          name: 'github-pages-1'

#      - name: Set artifact ID output
#        run: echo "::set-output name=artifact_id::${{ steps.upload-coverage-artifact.outputs.artifact_id }}"
#        id: documentation-artifact

      - name: Upload artifact 2
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./document
          name: 'github-pages-2'

#      - name: Set artifact ID output 2
#        run: echo "::set-output name=artifact_id::${{ steps.upload-coverage-artifact.outputs.artifact_id }}"
#        id: document-artifact