name: Pre-publish

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: "Run PR preparation steps"
        uses: ./.github/actions/pr-preparation
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Check for changed packages"
        shell: bash --noprofile --norc {0}
        run: |
          # note: use Lerna to detect changes in packages
          npx lerna changed --all --json
          # note: if no changes, set an environment variable to skip the subsequent steps
          if [ $? -eq 1 ]
          then
            echo "NO_CHANGED_PACKAGES=true" >> $GITHUB_ENV
            exit 0
          fi

      - name: "Version and publish"
        if: env.NO_CHANGED_PACKAGES != 'true'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          # To deploy the application with the latest changes, packages versions must be up to date.
          npx lerna version --conventional-commits --conventional-prerelease --no-changelog --preid "alpha" --yes
          npx lerna publish from-git --dist-tag alpha --yes

      - name: "Update package.json with latest library version"
        if: env.NO_CHANGED_PACKAGES != 'true'
        run: |
          # To deploy the application with the latest changes, packages versions must be up to date.
          package_names=("date-renderer" "date-logic") # List of package names to update
          
          # To deploy the application with the latest changes, packages versions must be up to date.
          for pkg in "${package_names[@]}"; do
            latest_version=$(npm view "@zidabah/$pkg" dist-tags.alpha 2>/dev/null)
          
            # Check if npm show command was successful (exit code 0)
            if [ $? -eq 0 ]; then
              jq --arg latest_version "$latest_version" ".dependencies[\"@zidabah/$pkg\"] = \$latest_version" package.json > package.json.tmp
              mv package.json.tmp package.json
            else
              echo "Package '@zidabah/$pkg' doesn't have an alpha version."
            fi
          done

          # note: clean up temporary files
          rm -f package.json.tmp

          # note: install dependencies with the updated package.json
          npm install

      - name: "Commit and push changes"
        if: env.NO_CHANGED_PACKAGES != 'true'
        run: |
          # To deploy the application with the latest changes, packages versions must be up to date.
          git add package.json
          git commit -m "chore: update libraries to the latest version"
          git push