name: Pre-release packages

on:
  pull_request:
    types: [ opened, synchronize, reopened ] #clarify about types
    branches:
      - 'dev'

jobs:
  run-generic:
    name: Preparation
    permissions: write-all
    uses: ./.github/workflows/generic.pr.yml

  run-publish:
    name: "Version and publish"
    if: env.NO_CHANGED_PACKAGES != 'true'
    run: |
      git config user.name "${{ github.actor }}"
      git config user.email "${{ github.actor }}@users.noreply.github.com"

      branch_name="${{ github.event.pull_request.head.ref }}"
      echo "Branch name: $branch_name"
      ticket_number=$(echo "$branch_name" | sed -n 's/[Zz][Ee][Nn]-\([0-9]\+\).*/\1/p')
      echo "Ticket number: $ticket_number"

      # note: use Lerna to version packages based on conventional commits, build, and publish
      npx lerna version --conventional-commits --conventional-prerelease --no-changelog --preid "beta.${ticket_number}" --yes
      npx lerna publish from-git --yes
#
#      - uses: ./.github/workflows/generic.version-bump.yml