name: Pre-Publish

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev

permissions: write-all

jobs:
  pre-publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          clean: true
          fetch-depth: 0

      - name: "Use NodeJS 18"
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: "Setup npm"
        run: |
          npm set @zidabah:registry=https://npm.pkg.github.com
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: "Install dependencies"
        run: |
          npm ci

      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          
          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          npx lerna publish from-git --yes