name: Publish

on:
  push:
    branches:
      - main
      - dev

env:
  GIT_SSH_COMMAND: ssh -i deploy_key

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          clean: true
          fetch-depth: 0

      - name: "Use NodeJS 18"
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: "Setup npm"
        run: |
          npm set @zidabah:registry=https://npm.pkg.github.com
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: "Install dependencies"
        run: |
          npm ci

      - name: "Version and publish"
        with:
          token: ${{secrets.lernav2}}
      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          npx lerna publish from-git --yes

      - name: "Update package.json with latest library version"
        run: |
          package_names=("date-renderer" "date-logic") # List of package names to update
          for pkg in "${package_names[@]}"; do
            latest_version=$(npm view "@zidabah/$pkg" version)
            jq --arg latest_version "$latest_version" ".dependencies[\"@zidabah/$pkg\"] = \$latest_version" package.json > package.json.tmp
            mv package.json.tmp package.json
          done

      - name: "Commit and push changes"
        run: |
          git add package.json
          git commit -m "Update libraries to the latest version"
          git push