name: Publish

on:
  push:
    branches:
      # note: only for dev branch since we need to release packages only once
      - dev

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Run PR preparation steps"
        uses: ./.github/actions/pr-preparation
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Check for changed packages"
        shell: bash --noprofile --norc {0}
        run: |
          # note: use Lerna to detect changes in packages
          npx lerna changed --all --json
          # note: if no changes, set an environment variable to skip the subsequent steps
          if [ $? -eq 1 ]
          then
            echo "NO_CHANGED_PACKAGES=true" >> $GITHUB_ENV
            exit 0
          fi

      - name: "Version and publish"
        if: env.NO_CHANGED_PACKAGES != 'true'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          # To deploy the application with the latest changes, packages versions must be up to date.
          npx lerna version --conventional-commits --conventional-graduate --no-changelog --exact --amend --yes
          npx lerna publish from-git --yes
          
          git pull
          git push